<?php  require_once('materials_box.html'.php); require_once(APP.'presentation/VarsContainer.php');
			 VarsContainer::load('BUILDING'); ?> 
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['1']['NAME'];?>&b=1"><?php echo VarsContainer::$display['BUILDING']['1']['NAME'];?></a>  Level: <?php echo VarsContainer::$display['BUILDING']['1']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['2']['NAME'];?>&b=2"> <?php echo VarsContainer::$display['BUILDING']['2']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['2']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['3']['NAME'];?>&b=3"> <?php echo VarsContainer::$display['BUILDING']['3']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['3']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['4']['NAME'];?>&b=4"> <?php echo VarsContainer::$display['BUILDING']['4']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['4']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['5']['NAME'];?>&b=5"> <?php echo VarsContainer::$display['BUILDING']['5']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['5']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['6']['NAME'];?>&b=6"> <?php echo VarsContainer::$display['BUILDING']['6']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['6']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['7']['NAME'];?>&b=7"> <?php echo VarsContainer::$display['BUILDING']['7']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['7']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['8']['NAME'];?>&b=8"> <?php echo VarsContainer::$display['BUILDING']['8']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['8']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['9']['NAME'];?>&b=9"> <?php echo VarsContainer::$display['BUILDING']['9']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['9']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['10']['NAME'];?>&b=10"> <?php echo VarsContainer::$display['BUILDING']['10']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['10']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['11']['NAME'];?>&b=11"> <?php echo VarsContainer::$display['BUILDING']['11']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['11']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['12']['NAME'];?>&b=12"> <?php echo VarsContainer::$display['BUILDING']['12']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['12']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['13']['NAME'];?>&b=13"> <?php echo VarsContainer::$display['BUILDING']['13']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['13']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['14']['NAME'];?>&b=14"> <?php echo VarsContainer::$display['BUILDING']['14']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['14']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['15']['NAME'];?>&b=15"> <?php echo VarsContainer::$display['BUILDING']['15']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['15']['LEVEL'];?><br />
Name:<a href="?page=building_<?php echo VarsContainer::$display['BUILDING']['16']['NAME'];?>&b=16"> <?php echo VarsContainer::$display['BUILDING']['16']['NAME'];?></a> Level: <?php echo VarsContainer::$display['BUILDING']['16']['LEVEL'];?><br />
